### ISSUE TITLE
Unable to connect to git.apache.org

### ISSUE THREAD

**Issue by rmcs2002** [apache/incubator-pagespeed-ngx#1666]
Whenever I try to build the docker image, I get these timeout errors that it can't reach git.apache.org:

```
Cloning into '/usr/src/modpagespeed/testing/gmock'...
Cloning into '/usr/src/modpagespeed/testing/gtest'...
Cloning into '/usr/src/modpagespeed/third_party/apr/src'...
fatal: unable to connect to git.apache.org:
git.apache.org[0: 52.202.80.70]: errno=Operation timed out

fatal: clone of 'git://git.apache.org/apr.git' into submodule path '/usr/src/modpagespeed/third_party/apr/src' failed
Failed to clone 'third_party/apr/src'. Retry scheduled
Cloning into '/usr/src/modpagespeed/third_party/aprutil/src'...
fatal: unable to connect to git.apache.org:
git.apache.org[0: 52.202.80.70]: errno=Operation timed out

fatal: clone of 'git://git.apache.org/apr-util.git' into submodule path '/usr/src/modpagespeed/third_party/aprutil/src' failed
Failed to clone 'third_party/aprutil/src'. Retry scheduled
```

Anyone else having this issue?

**Comment by Lofesa** [comment]
Hi @rmcs2002 
The git.apache.org don´t exist anymore. Change any reference for it in the `.gitmodules`  to `https://github.com/apache/`
You can read [here](https://github.com/apache/incubator-pagespeed-ngx/issues/1662#issuecomment-534907219) and [here](https://github.com/apache/incubator-pagespeed-mod/pull/1957)

**Comment by rmcs2002** [comment]
Hi @Lofesa 

Thanks for your reply. 

Maybe I'm missing something obvious (not familiar with submodules) but in the [.gitmodules of this repository](https://github.com/apache/incubator-pagespeed-ngx/blob/master/.gitmodules), I don't see any reference to git.apache.org?

**Comment by Lofesa** [comment]
Hi @rmcs2002 
Not in this repository but in https://github.com/apache/incubator-pagespeed-mod 
In the compilated files or in latest versions  is not changed, but is the last [commit](https://github.com/apache/incubator-pagespeed-mod/commit/f5e13dde1f1f830b7cf37e68e848d1243a70a60a) to the github repo.
Maybe you need to check it in the psol folder. Pagespeed for nginx need a library ( psol ) that come from pagespeed for apache.
Or perhaps I´m worng and the changes need to be done in some files in the docker, but I can´t find it.

**Comment by ygm521** [comment]
@rmcs2002 Have you solved it? How to solve it?

**Comment by ygm521** [comment]
@Lofesa  Have you solved it? How to solve it?

**Comment by Lofesa** [comment]
@ygm521 
I don´t know how to do it in docker.
If you build mod_pagespeed from scratch you nee to change .gitmodules
If you build ngx_pagespeed you need to chose the includes pagespeed_automatic library

**Comment by rmcs2002** [comment]
I don't understand where these old submodules come from. This step fetches the pagespeed repo:

```
Step 6/49 : RUN git clone -b ${MOD_PAGESPEED_TAG}               --recurse-submodules               --depth=1               -c advice.detachedHead=false               -j`nproc`               https://github.com/apache/incubator-pagespeed-mod.git               modpagespeed     ;
 ---> Running in 60a66a8cebb5
```

The step above fetches the old submodules:

```
Cloning into 'modpagespeed'...
[output omitted]
Submodule 'third_party/apr/src' (git://git.apache.org/apr.git) registered for path 'third_party/apr/src'
Submodule 'third_party/aprutil/src' (git://git.apache.org/apr-util.git) registered for path 'third_party/aprutil/src'
[output omitted]
```

When we look at the [.gitmodules file](https://github.com/apache/incubator-pagespeed-mod/blob/master/.gitmodules) of the pagespeed repository, we see for example:

```
[submodule "third_party/apr/src"]
	path = third_party/apr/src
	url = https://github.com/apache/apr.git
```

Which shows the correct repository URL.

**Comment by rmcs2002** [comment]
Ah wait, I have to check the correct tag:

[1.13.25.2 tag](https://github.com/apache/incubator-pagespeed-mod/blob/v1.13.35.2/.gitmodules)

Now the question is how to change the Dockerfile to use the new gitmodules file...

**Comment by rmcs2002** [comment]
I'm messing around a [bit with a fork that has an updated .gitmodules file](https://github.com/rmcs2002/incubator-pagespeed-mod/tree/fixed-gitmodules-apache-urls) and changed the Dockerfile a bit:

```
RUN git clone -b fixed-gitmodules-apache-urls \
              --depth=1 \
              -c advice.detachedHead=false \
              -j`nproc` \
              https://github.com/rmcs2002/incubator-pagespeed-mod.git \
    ;

RUN ls
RUN cd incubator-pagespeed-mod && \
git submodule sync --recursive && \
git submodule update --init --recursive
```

It uses the correct github.com/apache URLs now but I run into another error:

```
Submodule path 'third_party/grpc/src/third_party/zlib': checked out 'cacf7f1d4e3d44d871b605da3b647f07d718623f'
Submodule path 'third_party/hiredis/src': checked out '010756025e8cefd1bc66c6d4ed3b1648ef6f1f95'
error: Server does not allow request for unadvertised object 493b43719686d9667831da5d5e063fb8fcd8c604
Fetched in submodule path 'third_party/httpd/src', but it did not contain 493b43719686d9667831da5d5e063fb8fcd8c604. Direct fetching of that commit failed.
```
@Lofesa any idea how to fix this?

**Comment by Lofesa** [comment]
Hi @rmcs2002 
I see this before, in the comment of the PR that updates `.gitmodules`
Maybe you need to add --depth=100 to the line 
`git submodule sync --recursive --depth=100 && \`

or some other number you consider. For reference I have read [this](https://superuser.com/questions/1240216/what-does-the-git-error-message-server-does-not-allow-request-for-unadvertised)

The reference to the httpd object exists, as you can [see](https://github.com/apache/httpd/tree/493b43719686d9667831da5d5e063fb8fcd8c604)

`git.apache.org` was down for a device crash and then `apache.org` had decided to change to github urls, maybe some things don´t work as spected.

Maybe you can ask @mmilitzer, the user that report the same issue in the [update .gitmodules PR](https://github.com/apache/incubator-pagespeed-mod/pull/1957)

**Comment by mmilitzer** [comment]
I can't really help much on this because I still have this problem and just simply gave up when nobody could reproduce it.

So I see too that the commit hash exists in the github web UI (like the link that @Lofesa provided) but when you actually clone the repo with git on the commandline, then the commit hash does not exist:

git clone https://github.com/apache/httpd.git
git branch --contains 493b43719686d9667831da5d5e063fb8fcd8c604
error: no such commit 493b43719686d9667831da5d5e063fb8fcd8c604

@Lofesa: Does the above work for you?

I see that this commit is a tag to 2.2.29 and I get this tag too after I clone the repo, just that the commit hash is a different one:

git checkout tags/2.2.29
git log -1 --format="%H"
cef6805cb18886c5454a38f3501c5e3c990c0b3d

So I wonder if something is broken with this github repo and if the github web UI is somehow out of sync with the actual repo data - perhaps because Apache re-mirrored the repo freshly from SVN after their device crash. But I don't know...

**Comment by Lofesa** [comment]
Hi @mmilitzer 
I have tried 
```
git clone https://github.com/apache/httpd.git
git branch --contains 493b43719686d9667831da5d5e063fb8fcd8c604
```
and get the same error. Tried4
`git clone --depth=1000000 https://github.com/apache/httpd.git`
and get the same error.

And apparently the `493b43719686d9667831da5d5e063fb8fcd8c604` and the `cef6805cb18886c5454a38f3501c5e3c990c0b3d` commits are the same, they have the same 
`git-svn-id: https://svn.apache.org/repos/asf/httpd/httpd/tags/2.2.29@1619850 13f79535-47bb-0310-9956-ffa450edef68`

So I think are 2 objects (the github commits) that references the same thing in git-svn.

Maybe things must be changed to `cef6805cb18886c5454a38f3501c5e3c990c0b3d` as far as this commit don´t throw any error.

I can´t see how to post an issue to httpd repo.

**Comment by Lofesa** [comment]
Maybe we have this [issue](https://help.github.com/en/github/committing-changes-to-your-project/commit-exists-on-github-but-not-in-my-local-clone)
If the branch is deleted or force pushed we are out of luck.

**Comment by Lofesa** [comment]
@mmilitzer @rmcs2002 
Take a look at this
https://github.com/apache/incubator-pagespeed-mod/pull/1957#issuecomment-548661072

**Comment by akinmetin** [comment]
When I try to build a docker image using
```
--recurse-submodules \
              --depth=1 \
              -c advice.detachedHead=false \
              -j`nproc` \
              https://github.com/apache/incubator-pagespeed-mod.git \
              modpagespeed \
```
I get this error;
```
fatal: clone of 'git://git.apache.org/apr.git' into submodule path '/usr/src/modpagespeed/third_party/apr/src' failed
Failed to clone 'third_party/apr/src' a second time, aborting
Cloning into '/usr/src/modpagespeed/third_party/aprutil/src'...
fatal: unable to connect to git.apache.org:
git.apache.org[0: 52.202.80.70]: errno=Connection refused
```
@Lofesa

**Comment by Lofesa** [comment]
I don´t know much more than is in this thread.
The problem is that the Dockerfile point to a tag  ( v1.13.35.2 ) that have a wrong .gitmodules.
Maaybe you need to update to the newest tag ( v1.14.36.1 ). I think in this version is solved

**Comment by akinmetin** [comment]
Now I have this error like @rmcs2002 .
```
Submodule path 'third_party/grpc/src/third_party/zlib': checked out 'cacf7f1d4e3d44d871b605da3b647f07d718623f'
Submodule path 'third_party/hiredis/src': checked out '010756025e8cefd1bc66c6d4ed3b1648ef6f1f95'
error: Server does not allow request for unadvertised object 493b43719686d9667831da5d5e063fb8fcd8c604
Fetched in submodule path 'third_party/httpd/src', but it did not contain 493b43719686d9667831da5d5e063fb8fcd8c604. Direct fetching of that commit failed.
```

I added your suggested codes @Lofesa  but still not working.
My final code is;
```
RUN git clone -b ${MOD_PAGESPEED_TAG} \
              --recurse-submodules \
              --depth=1 \
              -c advice.detachedHead=false \
              -j`nproc` \
              https://github.com/apache/incubator-pagespeed-mod.git \
              modpagespeed \
    ;

RUN cd incubator-pagespeed-mod && \
git submodule sync --recursive --depth=100 && \
git submodule update --init --recursive
```

**Comment by Lofesa** [comment]
Ummm seems you don´t have changed the tag.
What value have the MOD_PAGESPEED_TAG?
In v1.13.35.2, third_party/httpd/src points to some hash that start with 493b437
but in version v1.14.36.1 point to some hash that start with cef6805cb

If you go to mod_pagespeed code and change the branch between 35 and 36, you can see that the hash that third_party/httpd/src point are diferent

**Comment by akinmetin** [comment]
> Ummm seems you don´t have changed the tag.
> What value have the MOD_PAGESPEED_TAG?
> In v1.13.35.2, third_party/httpd/src points to some hash that start with 493b437
> but in version v1.14.36.1 point to some hash that start with cef6805cb
> 
> If you go to mod_pagespeed code and change the branch between 35 and 36, you can see that the hash that third_party/httpd/src point are diferent

Problem is solved. No error when I download and re-upload this repo to my space.

**Comment by lucianosantana** [comment]
@Lofesa that's not correct. The change on the http reference was done in [this commit](https://github.com/apache/incubator-pagespeed-mod/commit/d41e302990ae90473ad5031e7936e46364d3cacc) from Nov 27th, while the tag [v1.14.36.1 was released on Nov 26th](https://github.com/apache/incubator-pagespeed-mod/releases/tag/v1.14.36.1).

As workaround I've temporarily changed the MOD_PAGESPEED_TAG to `master` and the container is built as expected.

**Comment by oschaaf** [comment]
That 1.14 release still is in flight; the tag will get updated to include the deposit update.

**Comment by xcellenceit** [comment]
Seems to work when I update the ARG MOD_PAGESPEED_TAG to use vlatest-stable in Dockerfile

**Comment by rmcs2002** [comment]
> While a new tag is not released, as workaround I've temporarily changed the MOD_PAGESPEED_TAG to `master` and the container is built as expected.

I gave this a try, but it still fails to build. Anything I am missing?

**Comment by Lofesa** [comment]
But with the same messages?

**Comment by rmcs2002** [comment]
Here's what I have:

Edited:

`incubator-pagespeed-ngx/docker/alpine-3.8/nginx-stable/Dockerfile`

Changed:

`ARG MOD_PAGESPEED_TAG=master`

Build:

`docker build -t some-content-ngxpagespeed .`

Error:
```
patching file pagespeed/kernel/image/gif_reader.cc
patching file pagespeed/kernel/image/image_converter.cc
patching file pagespeed/kernel/image/png_optimizer_test.cc
patching file third_party/libpng/libpng.gyp
Hunk 1 FAILED 22/22.
           'dependencies': [
             '../zlib/zlib.gyp:zlib',
           ],
+          'actions': [
+            {
+              'action_name': 'copy_libpngconf_prebuilt',
+              'inputs' : [],
+              'outputs': [''],
+              'action': [
+                'cp',
+                '-f',
+                '<(DEPTH)/third_party/libpng/src/scripts/pnglibconf.h.prebuilt',
+                '<(DEPTH)/third_party/libpng/src/pnglibconf.h',
+              ],
+            },
+          ],
           'msvs_guid': 'C564F145-9172-42C3-BFCB-6014CA97DBCD',
           'sources': [
+            'src/pngpriv.h',
             'src/png.c',
             'src/png.h',
             'src/pngconf.h',
+            'src/pngdebug.h',
             'src/pngerror.c',
-            'src/pnggccrd.c',
             'src/pngget.c',
+            'src/pnginfo.h',
             'src/pngmem.c',
             'src/pngpread.c',
             'src/pngread.c',
```

You were able to successfully build the container?

**Comment by Lofesa** [comment]
Hi
I don´t use containers..
But seem that the build fail cause the process make a patch to libpng.gyp and maybe these patch is not needed. take a look at https://github.com/apache/incubator-pagespeed-mod/blob/master/third_party/libpng/libpng.gyp and you can see that the chanches the patch do are in place.
The patch was made for an old version of the file, the file was changed so line numbers are not the same.
I see that in the build script is a for loop tp apply the patch files so you need to delete libpng16.patch

**Comment by rmcs2002** [comment]
Hi @Lofesa,

That did the job, thanks! I deleted the patch from the patches folder and the build works 👍
